### Success request - will return 200 OK with data
# Response example:
# HTTP/1.1 200 OK
# Content-Type: application/json
# Date: Tue, 19 Apr 2022 17:33:56 GMT
# Content-Length: 155
#
# [
#  { "random_number": 106 },
#  { "random_number": 211 },
#  { "random_number": 237 },
#  { "random_number": 445 },
#  { "random_number": 495 },
#  { "random_number": 466 },
#  { "random_number": 528 }
# ]
POST http://localhost:8990/multiplex
Content-Type: application/json

[
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000",
  "http://stub:8991/stub?limit=1000"
]
